namespace: ""
repository_prefix: ""

dbhost_visits: cgtn3gql0yfa.eu-west-3.rds.amazonaws.com:3306
dbname_visits: visitsdb
dbuser_visits: admin

dbhost_customers: cgtn3gql0yfa.eu-west-3.rds.amazonaws.com:3306
dbname_customers: customersdb
dbuser_customers: admin

dbhost_vets: cgtn3gql0yfa.eu-west-3.rds.amazonaws.com:3306
dbname_vets: vetsdb
dbuser_vets: admin