# Namespace where the application will be deployed
namespace: "qa"

# Prefix for the repository where Helm charts are hosted
repository_prefix: "myapp"

visits:
  # Hostname or IP address of the database server for the 'visits' service
  dbhost: "visits-db-host"
  # Name of the database for the 'visits' service
  dbname: "visits-db-name"
  # Username for connecting to the 'visits' database
  dbuser: "visits-db-user"